# Regulatrix config
# Only kbit units supported, parser does understand anything else.
# r2q: Optional rate to quantum divisor.  Use to remove syslog msgs, 1-100.
# Different qdiscs for inbound and outbound traffic.  Devices added if rates specified.
# Use different id's for each device, duplication on same qdisc is an error.
# Ceilings are optional.
#
# Regulate upload/download rates from a local network - e.g. br-lan - to an Internet
# interface (wan, wwan, etc.).  This is especially useful if you have Ring or similar
# cameras which will happily upload at 4k, but which will gracefully provide
# reasonable imagery at much lower rates (e.g. 300kbit) if you compel them to. Likewise,
# video downloaders may attempt to receive the highest resolution attainable but
# 720p might do just as well as 4k for many applications.  High rates of movement
# will require more data, low levels less.
#
# Ring recommendations for maximal requirements:
#  4k:		15Mbps
#  2k:		10Mbps
#  1536p:	2.5Mbps
#  1080p:	2Mbps
#  720p:	1Mbps
#
# MAC addresses are used to specify the devices for which bandwith should be regulated.
# Each device will be put in a separate class with its own guaranteed rate and ceiling.
#
# Separate qdiscs are set up for uploads and downloads.  Devices are added to them
# as required by the config.

config global
	option lan_dev "br-lan"			# Usually br-lan
	option lan_r2q "10"			# Default is 10
	option wan_dev "phy1-sta0"		# Usually wan
	option wan_r2q "10"
	option inbound_rate "50000kbit"		# Use kbit, parser likes them.
	option outbound_rate "5500kbit"
	option enable_inbound_filter "0"
	option enable_outbound_filter "0"

config device
	option device_name "RingStickUpCam"
	option mac_address "90:48:6C:3C:13:37"
	option outbound_rate "1000kbit"
	option outbound_ceil "2000kbit"
	option id "20"

config device
	option device_name "RingDoorbell"
	option mac_address "90:48:6C:F2:36:6E"
	option outbound_rate "300kbit"
	option id "21"

config device
	option device_name "Media Center 21"
	option mac_address "A3:09:D9:32:EE:BF"
	option inbound_rate "6000kbit"
	option inbound_ceil "10000kbit"
	option id "22"

config device
	option device_name "Both up and down qdiscs"
	option mac_address "A3:09:D9:32:EE:BF"
	option inbound_rate "6000kbit"
	option inbound_ceil "10000kbit"
	option outbound_rate "1000kbit"
	option outbound_ceil "2000kbit"
	option id "22"
